# Updated GitHub Actions workflows

yaml version: 2.0

name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: npm install && npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment

      - name: Push to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Push to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 489395619894.dkr.ecr.eu-north-1.amazonaws.com
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest 489395619894.dkr.ecr.eu-north-1.amazonaws.com/your-ecr-repo:latest
          docker push 489395619894.dkr.ecr.eu-north-1.amazonaws.com/your-ecr-repo:latest

      - name: CI Guardrails
        run: |
          echo 'Ensure all environment variables are set properly before deployment.'
          # Additional guardrails can be added here.
